import { kumbhSans } from "@/utils/fonts";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <StoreProvider>
          <div className=" bg-secondary-light-gray dark:bg-primary-midnight min-h-screen">
            <Header />
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
